### ISSUE TITLE
请问，如何让您index.html中的 调整size的js  只工作在你的组件范围内，而不是全局

### ISSUE THREAD

**Issue by coderws** [k186/vue-wheel-scroll-datepikcer#1]
请问，如何让您index.html中的 调整size的js  只工作在你的组件范围内，而不是全局。
因为工作于全局，会影响其他已有的样式，处理不好，麻烦指点一下

**Comment by k186** [comment]
你好，建议使用升级版 https://github.com/k186/iosSelect 这个组件，现在这个适用范围和性能都不是很好。升级版需要你自己去实现日期的初始化

**Comment by coderws** [comment]
嗯，这个datapicker  主要是因为rem和px互相转换的问题。  我所有页面html的 font-size是按照62.5%来算的，组件是依靠计算出来的px 给到html标签font-size.计算的 .。在考虑 修改scss里的值，  所以请问作者，我考虑 修改scss里的值这个思路应该是可以的吧

**Comment by k186** [comment]
@coderws  也许可以,我那一套是用的基于阿里的适配方案 用的rem 然后index 里面的js 就是他的适配，不同手机下的body字体大小是不一样的,还是不建议使用这个了。修改css 也可以不过这个里面有点乱，需要一定的时间，主要修改高度 宽度 注意我里面用的 px2rem这个scss 方法 涉及了这个的基本都需要修改

**Comment by coderws** [comment]
嗯 同事给改好了。  iosSelect可能确实简易了一些，这个时间选择除了兼容还是很不错的

**Comment by k186** [comment]
@coderws  iosSelect 可以做的事更多，也方便扩展。现在这个当初也是为了赶进度写的。😄
